### ISSUE TITLE
Warning: Error in render: unused argument (standalone = FALSE)

### ISSUE THREAD

**Issue by martinbeliveau** [smouksassi/ggplotwithyourdata#11]
Seems like the table function stopped working for me. I get 
"Warning: Error in render: unused argument (standalone = FALSE)"

no matter what I try to put in X or Y.

**Comment by smouksassi** [comment]
Please update to latest table1 package                                                                                                                                                                                                                                                                                                                                                    From: notifications@github.comSent: April 28, 2017 1:37 PMTo: ggplotwithyourdata@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [smouksassi/ggplotwithyourdata] Warning: Error in render: unused argument (standalone = FALSE) (#11)  Seems like the table function stopped working for me. I get
"Warning: Error in render: unused argument (standalone = FALSE)"
no matter what I try to put in X or Y.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
