### ISSUE TITLE
Descriptive Stats Table issue numerical categories

### ISSUE THREAD

**Issue by martinbeliveau** [smouksassi/ggplotwithyourdata#9]
It seems there is an issue with the descriptive stats table when we use a numerical category (0 or 1). If we use "Treat as category" the table still recognizes the variable as continuous numeric and outputs the mean and SD. We have to do the work around of "recutting" the data into binned categories to get the proportions to show up (and then have to relabel the datacuts).

**Comment by smouksassi** [comment]
this is a broader issue ine the sense that the table does not use all the data management steps that are used for the plotting the table unstack the data and lose all the attributes and automatically convert the seemingly numerical variable into numeric. will be closing since the workaround is working
